"""Planning orchestration.

Phase 1 contains only a *stub* plan builder so the end-to-end path works (CLI →
plan object → Markdown → /plans) before any repo analysis or provider exists.
Later phases replace :func:`build_stub_plan` with a real pipeline that ranks
files, assembles context, calls a provider, and validates the response.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from codegraft.config import Config
from codegraft.models.plan import (
    AgentPrompt,
    Confidence,
    GenerationMetadata,
    ImplementationPlan,
    PlanPhase,
    PlannedFileChange,
    ReviewedFile,
    RiskItem,
    RiskSeverity,
    TestItem,
)


def build_stub_plan(request: str, repo_root: Path, config: Config) -> ImplementationPlan:
    """Return a representative, hand-built plan for the given *request*.

    This proves the contract and the rendering path. It does **not** look at the
    repository contents yet — that arrives in later phases.
    """

    return ImplementationPlan(
        title=request.strip().capitalize() or "Implementation Plan",
        feature_summary=(
            f'[STUB] This is a placeholder plan for the request: "{request.strip()}". '
            "Real repository analysis and model-generated planning are added in later phases."
        ),
        assumptions=[
            "This output was generated by the Phase 1 stub, not an LLM.",
            "No repository files were actually read to produce this plan.",
        ],
        open_questions=["Which provider and model should generate the real plan?"],
        relevant_architecture=(
            "[STUB] The deterministic analysis layer (discovery, ranking, snippets) "
            "is not implemented yet, so no architecture summary is available."
        ),
        files_reviewed=[
            ReviewedFile(
                path="(none — stub)",
                why_it_matters="Placeholder; real evidence bundle arrives in Phase 3.",
                confidence=Confidence.low,
            )
        ],
        files_likely_to_modify=[
            PlannedFileChange(
                path="(unknown — stub)",
                expected_change="Determined by real ranking in a later phase.",
                reason="Stub plan has no repository evidence.",
            )
        ],
        data_model_changes=[],
        api_service_changes=[],
        ui_changes=[],
        implementation_phases=[
            PlanPhase(
                name="Phase A: replace this stub",
                goal="Wire up real repo analysis and a provider call.",
                likely_files=["src/codegraft/planning/service.py"],
                tasks=[
                    "Implement repo discovery and ranking.",
                    "Assemble a context bundle.",
                    "Call a provider for a structured plan.",
                ],
                acceptance_criteria=[
                    "A real plan is generated from actual repo evidence.",
                ],
                validation=["Run codegraft plan against a fixture repo."],
            )
        ],
        risks=[
            RiskItem(
                description="Treating this stub output as a real plan.",
                severity=RiskSeverity.high,
                mitigation="Look for the [STUB] markers; replace in later phases.",
            )
        ],
        test_plan=[
            TestItem(
                kind="unit",
                description="Renderer always emits every required section.",
                target="tests/test_renderer.py",
            )
        ],
        claude_code_prompts=[
            AgentPrompt(
                phase_name="Phase A: replace this stub",
                prompt=(
                    "Implement the real codegraft planning pipeline: repository "
                    "discovery, ranking, snippet extraction, and a provider call "
                    "returning a validated ImplementationPlan."
                ),
            )
        ],
        definition_of_done=[
            "codegraft plan produces a real, evidence-backed plan (not this stub).",
        ],
        metadata=GenerationMetadata(
            provider="stub",
            model="none",
            repo_root=str(repo_root.resolve()),
            timestamp=datetime.now().isoformat(timespec="seconds"),
            ranked_file_count=0,
            reviewed_file_count=0,
        ),
    )
